name: Test Node.js Package

on:
  workflow_dispatch:
      inputs:
          coverageUpload:
            description: 'Upload coverage to Code Climate and Codecov?'
            required: false
            default: 'no'
  push:
    branches:
      - 'master'
  release:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install yarn
        run: npm i -g yarn
      
      - name: Install everything
        run: yarn
      
      - name: Run tests
        run: yarn run test
      
      - name: Compress the coverage report
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r coverage.zip coverage
      
      - name: Upload the report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.zip
  coverage-codeclimate:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.inputs.coverageUpload == 'yes'}}
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Node.js v12
          uses: actions/setup-node@v1
          with:
            node-version: 12

        - name: Install yarn
          run: npm i -g yarn

        - name: Install everything
          run: yarn
        
        - name: Generate coverage and upload to Code Climate
          uses: paambaati/codeclimate-action@v2.7.4
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ID }}
          with:
            coverageCommand: yarn run test

  coverage-codecov:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.inputs.coverageUpload == 'yes'}}
    steps:
        - name: Download coverage report
          uses: actions/download-artifact@v2
          with:
            name: coverage
        - name: Extract coverage report
          uses: montudor/action-zip@v0.1.0
          with:
            args: unzip -qq coverage.zip -d coverage
        
        - name: Upload to codecov
          uses: codecov/codecov-action@v1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
  
  
          